<!DOCTYPE html>
<html>
<head>
	<title>	</title>
	<style>
		p{
			font-family: Arial;
			font-size: 15px;
		}

		label{
			font-family: Arial;
			font-size: 15px;
		}

		table, th, td {
		  	border: 1px solid black;
		  	border-collapse: collapse;
		  	padding: 3px 10px;
		 	font-family: Arial;
			font-size: 14px; 	
		}
	</style>
</head>
<body>
	<p>Dear {{ $data['department_name'] }},</p>
	<p>Good day! </p>
	<p>Please generate necessary containment /corrective/ systemic actions on each Nonconformity or highlighted opportunities for Improvement and submit to QAD on or before  the due date specified below.</p>
	<table border="1">
		<thead>
			<tr>
				<th>No.</th>
				<th>Issued Date</th>
				<th>Audit Date</th>
				<th>Auditors</th>
				<th>Deadline of Submission</th>
				<th>Audit Type</th>
				<th>Responsible Department</th>
				<th>Statement of Findings</th>
				<th>Audit Status</th>
			</tr>
		</thead>
		<tbody>
			@for($index = 0; $index < count($data['data']); $index++)
				@php
					$col_data = collect($data['data'][$index]->internal_departments);
					$arr_department_names = [];

					$arr_department_names = $col_data->flatten(1)->pluck('department_info')->flatten(1)->pluck('department_name')->flatten(1);

					$department_count = count($arr_department_names);
					$department_names = $arr_department_names[0];
					$arr_final_department_names = [];

					for($index2 = 0; $index2 < count($arr_department_names); $index2++){
						$arr_final_department_names[] = $arr_department_names[$index2];
					}
					$department_names = implode(", ", $arr_final_department_names);

					// Audit Date
					$audit_date = '';
			        if($data['data'][$index]['audit_date_from'] != $data['data'][$index]['audit_date_to']){
			            $audit_date = \Carbon\Carbon::parse($data['data'][$index]['audit_date_from'])->toFormattedDateString() . ' - ' . \Carbon\Carbon::parse($data['data'][$index]['audit_date_to'])->toFormattedDateString();
			        }
			        else{
			            $audit_date = \Carbon\Carbon::parse($data['data'][$index]['audit_date_from'])->toFormattedDateString();
			        }

				@endphp

				<tr>
					<td>{{ $data['data'][$index]['internal_audit_id'] }}</td>
					<td>{{ \Carbon\Carbon::parse($data['data'][$index]['audit_findings_issued_date'])->toFormattedDateString() }}</td>
					<td>{{ $audit_date }}</td>
					<td>{{ $data['data'][$index]['auditors'] }}</td>
					<td>{{ \Carbon\Carbon::parse($data['data'][$index]['deadline_of_submission'])->toFormattedDateString() }}</td>

					@php
						$audit_type = 'EMS System';

						if($data['data'][$index]['audit_type'] == 2){
							$audit_type = 'QMS System';
						}
						else if($data['data'][$index]['audit_type'] == 3){
							$audit_type = 'Process';
						}
						else if($data['data'][$index]['audit_type'] == 4){
							$audit_type = 'Product';
						}
					@endphp

					<td>{{ $audit_type }}</td>

					<td>{{ $department_names }}</td>
					<td style="max-width: 500px;">{!! nl2br(e($data['data'][$index]['statement_of_findings'])) !!}</td>

					@php
						$audit_stat = 'For Improvement Plan';

						if($data['data'][$index]['audit_stat'] == 2){
							$audit_stat = 'For Close Out';
						}
						else if($data['data'][$index]['audit_stat'] == 3){
							$audit_stat = 'Closed';
						}
					@endphp
					<td>{{ $audit_stat }}</td>
				</tr>
			@endfor
		</tbody>
	</table>

	<br><br><br>

	<label>For more info, pleas e log-in to your RapidX account. Go to <a href="http://rapidx/RapidX" target="_blank">http://rapidx/RapidX</a></label><br>
	<label>This E-mail is automatically generated by the RapidX.</label><br>
	<label>Don't reply to this e-mail, this is only a notification created by the system, Thank you!</label><br>

	<br><br>

	<p>Quality Assurance Department</p>

	<br><br>

	<label><b>Notice of Disclaimer:</b></label><br>
	<label>This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message. Any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.</label>

</body>
</html>